# Generated by Django 4.2 on 2026-03-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_email_verification_fields'),
        ('users', '0002_profile_is_seller'),
    ]

    operations = [
    ]
