# Generated by Django 4.2 on 2026-03-31 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def gen_uuids(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    for row in Profile.objects.all():
        row.wishlist_share_token = uuid.uuid4()
        row.save(update_fields=['wishlist_share_token'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_merge_20260331_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_delivery_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='service_areas',
            field=models.TextField(blank=True, help_text='Comma-separated city names'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_deliveries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('bike', 'Bike'), ('scooter', 'Scooter'), ('car', 'Car'), ('van', 'Van')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='wishlist_share_token',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(gen_uuids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='wishlist_share_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
